# -*- mode: ruby -*-
# vi: set ft=ruby :       

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.define "freebsd1" do |ubuntu1|
    freebsd1.vm.box = "punktde/freebsd-111-zfs"
    freebsd1.vm.hostname = "freebsd1"
    freebsd1.vm.network "private_network", ip: "192.168.33.110"
  end

  config.vm.define "freebsd2" do |ubuntu2|
    freebsd2.vm.box = "punktde/freebsd-111-zfs"
    freebsd2.vm.hostname = "freebsd2"
    freebsd2.vm.network "private_network", ip: "192.168.33.120"
  end

  config.vm.define "freebsd3" do |freebsd3|
    freebsd3.vm.box = "punktde/freebsd-111-zfs"
    freebsd3.vm.hostname = "freebsd3"
    freebsd3.vm.network "private_network", ip: "192.168.33.130"
  end
end
